name: CI for Pull-Requests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'AsyncStateMachine.sln'
      - '**/ci.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'AsyncStateMachine.sln'
      - '**/ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          include-prerelease: false
          
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build solution
        run: dotnet build AsyncStateMachine.sln --configuration Release --no-restore 

      - name: Run UnitTests
        run: dotnet test --no-restore --no-build --configuration Release
        
      - name: Build nuget package
        run: dotnet pack src/AsyncStateMachine/AsyncStateMachine.csproj --configuration Release
        
      - name: Publish nuget package
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: dotnet nuget push src/AsyncStateMachine/AsyncStateMachine\bin\Release\*.nupkg -s nuget.org --api-key ${{ secrets.NUGET_API_KEY }}      
